### ISSUE TITLE
"Mailing list" signup

### ISSUE THREAD

**Issue by vielmetti** [WorksOnArm/worksonarm-news#12]
There should be a way for interested people to sign up to join a mailing list that will get news, in addition to all of the news I'm pushing out.

Either self-host this or put on a mailing list service (thinking about http://groups.io)

**Comment by vielmetti** [comment]
I'm handling these right now with manual signups and a bcc list out of Gmail, which isn't quite good enough.

Groups.io has some kind of Github integration, see:

> Have an open source project and need a group to discuss it? Groups.io is great for those. Full Github integration keeps people up to date on development of your open source project. Post using Markdown with syntax highlighting.

hey! that would be good, I have Markdown.

**Comment by vielmetti** [comment]
https://groups.io/g/worksonarm-news is the group, pending verification.

**Comment by vielmetti** [comment]
groups.io on hold pending marketing coordination, this might go out in intercom instead.

**Comment by luxas** [comment]
Please notify me when the mailing list is ready...

**Comment by vielmetti** [comment]
I'll make sure you get a copy in your inbox, @luxas !

**Comment by vielmetti** [comment]
New web site will have a newsletter driven by Mailchimp.

**Comment by vielmetti** [comment]
Mailchimp newsletter is up, and there's 100 or so signups. Closing.
