### ISSUE TITLE
Try "Gitbook"

### ISSUE THREAD

**Issue by vielmetti** [WorksOnArm/worksonarm-news#29]
It turns out that by adding a handful of files I can format this as though it were a book, sort of. See

https://vielmetti.gitbooks.io/works-on-arm-news/content/

for another view of Works on ARM News. This is a presentation that's a smidgeon easier to browse, which is nice.

**Comment by luxas** [comment]
Nice :+1: !

**Comment by janwillies** [comment]
indeed, very cool!

2017-06-28 11:52 GMT+02:00 Lucas Käldström <notifications@github.com>:

**Comment by remonlam** [comment]
Looks great!

**Comment by vielmetti** [comment]
Gitbook supports editing in a branch, and (crucially) also has sync with Github. I'll edit at least some of this issue in vim once I get the branch naming straight.

**Comment by vielmetti** [comment]
Let's call this a success and done for now.
