### ISSUE TITLE
Works on ARM website: Kubernetes

### ISSUE THREAD

**Issue by vielmetti** [WorksOnArm/worksonarm-news#34]
Right now https://www.worksonarm.com/kubernetes/ is a blank page with two upvotes; fix it to include current 1.7 information, to link for WOA 11 news release. (#32)

**Comment by vielmetti** [comment]
Bump this, needs a conversation with @luxas to determine what indeed one should say about Kubernetes on ARM64.

See also #64

**Comment by luxas** [comment]
What information do you need?

**Comment by vielmetti** [comment]
Bump this to a priority focus before Kubecon.

**Comment by vielmetti** [comment]
Page moved to https://www.worksonarm.com/explore/kubernetes/ - if there is more to say about a newest release of Kubernetes this can open in a new issue. Closing as done.
