### ISSUE TITLE
Works on ARM website: Docker

### ISSUE THREAD

**Issue by vielmetti** [WorksOnArm/worksonarm-news#37]
Docker info on the WOA website at http://worksonarm.com/explore/docker is at least a month stale; update it with 17.06-ce info including build instructions/results.

**Comment by luxas** [comment]
There's no support for armv6 (RPi 0, 1) anymore either IIRC
cc @alexellis

**Comment by StefanScherer** [comment]
There is a PR 11 in docker-ce-packaging repo, but no comments right now.

**Comment by alexellis** [comment]
Should probably mention that Docker support was dropped for ARMv6 for 17.06. It may be resumed in 17.07.

Currently there is breakage even for Docker CE 17.05 when installing on ARMv6 - should get an update on that in a few days.

**Comment by alexellis** [comment]
Isn't it unlikely that the original PR https://github.com/docker/docker-ce-packaging/pull/11 would get merged? Probably would come from Docker Inc if support is reintroduced in 17.07.

**Comment by vielmetti** [comment]
Ubuntu instructions are stale.

For Ubuntu 16.04 LTS, install Docker 1.12.6 with apt-get install docker.io on the Packet Type 2A server.

I'm pretty sure you get 1.13.1 now. Confirm and update as needed. Otherwise this isn't too bad.
