### ISSUE TITLE
WOA: Does self-compile count?

### ISSUE THREAD

**Issue by FlorianHeigl** [WorksOnArm/worksonarm-news#43]
Hi,

I couldn't find a description of the criteria for listing. Does it need to be pre-packaged and with repos or is it OK if one needs to i.e. dpkg-buildpackage?

Two large-scale infra projects I love work well on ARM64 (and even older):

- The Cloud Management solution OpenNebula (www.opennebula.org) works fine on ARM. I've tested it with LXC running Debian Containers. But Xen and KVM should work alike. LXC was an addon, so using a widespread hypervisor instead of LXC is just more likely to be OK out of the box.
With LXC the footprint is so low that I got a "full-blown cloud thing" running on an ODROID C2.
One of my next weekend projects is to document how to cloudburst from that single mini puter to a nice cloud made up from packet.net 's 96core boxes.
(It's possible, just needs a writeup)

- The config management + continuous compliance project Rudder (www.rudder-project.org) also has slightly inofficial ARM clients since some time. I've tested from ARMv6 up to ARM64 without issues.

If you got any questions, please reach out!

**Comment by vielmetti** [comment]
@FlorianHeigl -

Thanks for bringing those two projects to my attention.  There aren't formal guidelines for inclusion into Works on ARM yet, but here's what I'm looking at:

* Lowest level: Build targets exist for ARM, and there's evidence that the code path has been exercised. One or more bugs are documented in the change tracking system specific to ARM. Documentation mentions ARM and any known gotchas. Latest release builds, and if there are any specific issues they are documented. At least one writeup somewhere that describes the process.

* Higher level: A continuous integration system exists, and there's an ARM builder that generally builds OK (green). Binary artifacts, if distributed, include ARM binaries. Recent release available from a mainstream distribution in binary form. Full support in documentation. 

* Highest level: full ARM support from a commercial vendor, who is prepared to stand behind the product and offer a support contract for money. 

For Rudder, I was able to find these issues:

* https://www.rudder-project.org/redmine/issues/10004
* https://www.rudder-project.org/redmine/issues/7203

which describes the process of building on ARM (ARMv7 and ARMv8) and apply one patch for systems that don't use dmidecocde. That's a start. 

As for OpenNebula, I see that there's commercial support for x86 systems, but no mention anywhere in the release notes at

* http://docs.opennebula.org/5.4/intro_release_notes/release_notes/platform_notes.html

of any kind of ARM support, so I'd like to be directed to where that discussion is going on.

Thanks!

**Comment by vielmetti** [comment]
@FlorianHeigl - I think this issue can be closed out, but since you brought it up I wanted to be sure that I checked with you first.

**Comment by FlorianHeigl** [comment]
Hi,

Please close it.
I gave up on asking people to simply get a **free** build host at linaro and running continous builds...
For reference: I have build both for ARM,  they work pretty well. There are only administrative issues.

**Comment by vielmetti** [comment]
Thanks @FlorianHeigl !
