### ISSUE TITLE
WOA 2 editorial calendar

### ISSUE THREAD

**Issue by vielmetti** [WorksOnArm/worksonarm-news#5]
Some notes for WOA 2

- from @luxas a talk at Kubecon
- from @luxas this kubeadm workshop tutorial https://github.com/luxas/kubeadm-workshop
- from @vielmetti Red Hat Summit trip report
- from @vielmetti @spf13 Hugo support for ARMv8 https://github.com/spf13/hugo/releases
- from Scaleway new virtualized ARMv8 service

**Comment by vielmetti** [comment]
I'd like to have something about 64-bit operating systems for the Raspberry Pi 3.

**Comment by vielmetti** [comment]
OpenBSD 6.1 and nginx support; via Jeff

**Comment by vielmetti** [comment]
Nixos to be sure, via Jacob

**Comment by vielmetti** [comment]
96Boards news (Hikey 960)

**Comment by vielmetti** [comment]
knight suggests Hashicorp's Vault

**Comment by JeffUnderhill** [comment]
Hi Ed,

Couple of links for you related to your comment above about Raspberry Pi 3:

1) https://www.suse.com/communities/blog/suse-linux-enterprise-server-raspberry-pi/ <-- from SUSECon end of last year
2) https://www.stackiq.com/stackiq-announces-support-for-suse-linux-enterprise-server-raspberry-pi-and-netapp-storage-arrays-in-major-new-release-stacki-4-0/ <-- from earlier this week

Hope this helps

**Comment by vielmetti** [comment]
OpenBSD 6.1 and NixOS did not make it into WOA 2, pushing forward into WOA 3. Also going to push all the Hashicorp tools to a later issue.
