### ISSUE TITLE
Kubernetes federated testing

### ISSUE THREAD

**Issue by vielmetti** [WorksOnArm/worksonarm-news#64]
Track progress of Kubernetes end-to-end testing on arm64.

One recent issue illustrates: https://github.com/kubernetes/kubernetes/issues/25730

Federated testing info: https://github.com/kubernetes/test-infra/blob/master/docs/federated_testing.md

Tracking issue for Kubernetes multi-arch from @luxas https://github.com/kubernetes/kubernetes/issues/38067

**Comment by luxas** [comment]
I actually experimented with this yesterday, how did you read my mind :stuck_out_tongue_closed_eyes: 
The doc is _really_ outdated, but I'm working my way through the stack now manually so we can do this super-easily for Packet+other machines to get coverage

**Comment by vielmetti** [comment]
If you can unwind the stack enough to get a good sense of a next step on Packet let me know and we'll make it happen.

**Comment by vielmetti** [comment]
Bump this up in priority to prepare for Kubecon.
