### ISSUE TITLE
Fedora 28 release for 2018-W20

### ISSUE THREAD

**Issue by vielmetti** [WorksOnArm/worksonarm-news#94]
Peter Robinson, @nullr0ute notes the Fedora 28 release, which was previewed in 2018-W17. Write up the full release information. (PR welcome)

**Comment by nullr0ute** [comment]
Main Fedora 28 release announcement here:
https://fedoramagazine.org/announcing-fedora-28/

AArch64 Server download, listed on the right in Other:
https://getfedora.org/server/download/

ARMv7 downloads:
https://arm.fedoraproject.org/

Other aarch64 deliverables:
https://alt.fedoraproject.org/alt/

**Comment by vielmetti** [comment]
I'm a little confused by this presentation @nullr0ute - there are two pages with "ARM servers", the one with the more bold presentation is the 32-bit version, and that page doesn't link to the 64-bit version. 

I think also you'll want to look at new brand guidelines for Arm (they have dropped the all-caps treatment). https://www.arm.com/company/policies/trademarks

**Comment by nullr0ute** [comment]
The Fedora page layouts are confusing, the aarch64 server is https://getfedora.org/server/download/ they are listed on the right under "other downloads"

The web sites are nothing to do with me, I have raised tickets already about their layout

**Comment by vielmetti** [comment]
Published in https://github.com/WorksOnArm/worksonarm-news/blob/master/2018-W20.md
